package liquidhacks.rallee.ralleebe.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;

@DynamoDBTable(tableName = "User")
public class UserDTO implements Serializable
{
	private String id;
	private String username;
	private String password;

	public UserDTO() {
		
	}
	
	//@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
	
    @DynamoDBHashKey
	@DynamoDBAttribute
	public String getUsername() {
		return username;
	}
	
	@DynamoDBAttribute
	public String getPassword() {
		return password;
	}
	
	public void setPassword(String password) {
		this.password = password;
	}

}